# Generated by Django 4.2.7 on 2026-01-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_userwallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userwallet',
            name='balance',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='user',
        ),
    ]
