# Generated by Django 4.2.7 on 2026-01-10 05:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_remove_userwallet_balance_remove_userwallet_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserWallet',
        ),
    ]
