# Generated by Django 4.2.7 on 2026-01-13 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_otpcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='seryal',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='account/%y/%m/%d/'),
        ),
    ]
