# Generated by Django 4.2.7 on 2026-01-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_user_seryal_user_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='qr_code_base64',
            field=models.CharField(blank=True, max_length=225, null=True),
        ),
    ]
