# Generated by Django 4.2.7 on 2026-01-14 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_user_qr_code_base64'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='کد معرف'),
        ),
    ]
