# Generated by Django 4.2.7 on 2026-01-20 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_user_referral_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='otpcode',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='انقضا'),
        ),
        migrations.AddField(
            model_name='otpcode',
            name='is_verified',
            field=models.BooleanField(default=False, verbose_name='احراز شده'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_authenticate',
            field=models.BooleanField(default=False, verbose_name='احراز هویت'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.PositiveSmallIntegerField(verbose_name='کد'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='otpcode',
            name='phone_number',
            field=models.CharField(max_length=11, verbose_name='شماره موبایل'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='فعال'),
        ),
        migrations.AlterField(
            model_name='user',
            name='qr_code_base64',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='QR کد'),
        ),
        migrations.AlterField(
            model_name='user',
            name='seryal',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='سریال کارت ملی'),
        ),
        migrations.AlterField(
            model_name='user',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='account/%y/%m/%d/', verbose_name='ویدئو احراز هویت'),
        ),
    ]
