# Generated by Django 4.2.7 on 2026-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_otpcode_expires_at_otpcode_is_verified_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='code',
            field=models.CharField(max_length=6, verbose_name='کد'),
        ),
    ]
