# Generated by Django 4.2.7 on 2025-11-08 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('category', models.CharField(choices=[('registration_auth', 'ثبت\u200cنام و احراز هویت'), ('investment', 'سرمایه\u200cگذاری'), ('market', 'بازار')], max_length=50, verbose_name='دسته\u200cبندی موضوع')),
                ('question', models.CharField(max_length=255, verbose_name='صورت سؤال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی؟')),
            ],
            options={
                'verbose_name': 'سؤال متداول',
                'verbose_name_plural': 'سؤالات متداول',
                'ordering': ['-created'],
            },
        ),
    ]
