# Generated by Django 4.2.7 on 2025-12-18 07:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0004_project_current_funding_project_total_budget'),
    ]

    operations = [
        migrations.CreateModel(
            name='Investment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('area', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='مساحت')),
                ('price_per_meter', models.PositiveIntegerField(verbose_name='قیمت هر متر')),
                ('base_amount', models.PositiveIntegerField(verbose_name='مبلغ خرید')),
                ('fee_amount', models.PositiveIntegerField(verbose_name='کارمزد')),
                ('tax_amount', models.PositiveIntegerField(verbose_name='مالیات')),
                ('total_payment', models.PositiveIntegerField(verbose_name='مبلغ قابل پرداخت')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=50)),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضای پرداخت')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to='project.project', verbose_name='پروژه')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'سرمایه\u200cگذاری',
                'verbose_name_plural': 'سرمایه\u200cگذاری\u200cها',
            },
        ),
        migrations.AddConstraint(
            model_name='investment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('user', 'project'), name='unique_pending_investment'),
        ),
    ]
