# Generated by Django 4.2.7 on 2025-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='area',
            field=models.DecimalField(decimal_places=6, max_digits=14, verbose_name='مساحت'),
        ),
    ]
