# Generated by Django 4.2.7 on 2025-12-27 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('project', '0006_remove_project_multiplier_project_investable_area'),
        ('investments', '0002_alter_investment_area'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='locked_area',
            field=models.DecimalField(decimal_places=6, default=0, help_text='متراژی که در sale های فعال قفل شده', max_digits=14),
        ),
        migrations.AddField(
            model_name='investment',
            name='sold_area',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='متراژ فروخته شده'),
        ),
        migrations.AlterField(
            model_name='investment',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='investments', to='project.project', verbose_name='پروژه'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='investment',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='investments', to=settings.AUTH_USER_MODEL, verbose_name='کاربر'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='InvestmentSale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('price_per_meter', models.PositiveIntegerField(verbose_name='قیمت هر متر')),
                ('selling_area', models.DecimalField(decimal_places=6, max_digits=14, verbose_name='متراژ قابل فروش')),
                ('status', models.CharField(choices=[('selling', 'در انتظار فروش'), ('sold', 'فروخته شده'), ('canceled', 'کنسل شده')], default='selling', max_length=50)),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ فروش')),
                ('base_amount', models.PositiveIntegerField(verbose_name='مبلغ خرید کاربر')),
                ('sale_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='انقضای فروش')),
                ('sold_area', models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='متراژ فروخته شده')),
                ('fee_amount', models.PositiveIntegerField(verbose_name='کارمزد')),
                ('tax_amount', models.PositiveIntegerField(verbose_name='مالیات')),
                ('total_payment', models.PositiveIntegerField(verbose_name='مبلغ قابل پرداخت')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان انقضای پرداخت')),
                ('buyer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='خریدار')),
                ('investment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to='investments.investment', verbose_name='سرمایه گذاری مرجع')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='فروشنده')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
