# Generated by Django 4.2.7 on 2026-01-08 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0003_investment_locked_area_investment_sold_area_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='investmentsale',
            options={'verbose_name': 'فروش سرمایه\u200cگذاری', 'verbose_name_plural': 'فروش سرمایه\u200cگذاری\u200cها'},
        ),
    ]
