# Generated by Django 4.2.7 on 2026-01-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0004_alter_investmentsale_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='investmentsale',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی'),
        ),
    ]
