# Generated by Django 4.2.7 on 2026-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('investments', '0005_investmentsale_is_featured'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='status',
            field=models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('paid', 'پرداخت شده'), ('canceled', 'لغو شده')], default='pending', max_length=50, verbose_name='وضعیت'),
        ),
    ]
