# Generated by Django 4.2.7 on 2026-01-08 09:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('sheba_number', models.CharField(max_length=26, verbose_name='شماره شبا')),
                ('card_number', models.CharField(max_length=16, verbose_name='شماره کارت')),
                ('bank_name', models.CharField(max_length=50, verbose_name='نام بانک')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_cards', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SuggestedDepositAmount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('amount', models.PositiveBigIntegerField(verbose_name='مبلغ پیشنهادی')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
            ],
            options={
                'verbose_name': 'مبلغ پیشنهادی',
                'verbose_name_plural': 'مبلغ\u200cهای پیشنهادی',
                'ordering': ['amount'],
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('balance', models.BigIntegerField(default=0, verbose_name='موجودی کل')),
                ('blocked_balance', models.BigIntegerField(default=0, verbose_name='موجودی بلوکه شده')),
                ('is_active', models.BooleanField(default=True, verbose_name='فعال')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='wallet', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WithdrawRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('amount', models.BigIntegerField(verbose_name='مبلغ برداشت')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10, verbose_name='وضعیت')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='زمان بررسی')),
                ('bank_card', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.creditcard', verbose_name='کارت مقصد')),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.wallet', verbose_name='کیف پول')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('amount', models.BigIntegerField(verbose_name='مقدار')),
                ('transaction_type', models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('purchase', 'Purchase')], max_length=10, verbose_name='نوع تراکنش')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=10, verbose_name='وضعیت تراکنش')),
                ('reference_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='کد مرجع')),
                ('authority', models.CharField(max_length=255, unique=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='payment.wallet', verbose_name='کیف پول')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
