# Generated by Django 4.2.7 on 2026-01-10 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='creditcard',
            options={'verbose_name': 'کارت اعتباری', 'verbose_name_plural': 'کارت های اعتباری'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'تراکنش', 'verbose_name_plural': 'تراکنش ها'},
        ),
        migrations.AlterModelOptions(
            name='wallet',
            options={'verbose_name': 'کیف پول', 'verbose_name_plural': 'کیف پول ها'},
        ),
        migrations.AlterModelOptions(
            name='withdrawrequest',
            options={'verbose_name': 'درخواست برداشت', 'verbose_name_plural': 'درخواست های برداشت'},
        ),
        migrations.AlterField(
            model_name='suggesteddepositamount',
            name='amount',
            field=models.PositiveBigIntegerField(help_text='تومان', verbose_name='مبلغ پیشنهادی'),
        ),
    ]
