# Generated by Django 4.2.7 on 2026-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0002_alter_creditcard_options_alter_transaction_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.BigIntegerField(default=0, help_text='تومان', verbose_name='موجودی کل'),
        ),
        migrations.AlterField(
            model_name='wallet',
            name='blocked_balance',
            field=models.BigIntegerField(default=0, help_text='تومان', verbose_name='موجودی بلوکه شده'),
        ),
    ]
