# Generated by Django 4.2.7 on 2025-12-04 06:20

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegistrationContractor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('full_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='نام شرکت')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل')),
                ('phone', models.CharField(blank=True, max_length=11, null=True, verbose_name='شماره تماس')),
                ('contractor_type', models.TextField(verbose_name='نوع سازنده')),
                ('is_checked', models.BooleanField(default=False, verbose_name='بررسی شده؟')),
            ],
            options={
                'verbose_name': 'درخواست',
                'verbose_name_plural': 'درخواست ها',
                'ordering': ('-created',),
            },
        ),
        migrations.AlterModelOptions(
            name='contractor',
            options={'verbose_name': 'سازنده', 'verbose_name_plural': 'سازنده ها'},
        ),
        migrations.AddField(
            model_name='contractor',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='تگ آلت'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, verbose_name='درباره کمپانی'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='image',
            field=models.ImageField(default='', upload_to='contractors/%y/%m/%d/', verbose_name='عکس برند'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی؟'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='name',
            field=models.CharField(default='test', max_length=150, verbose_name='نام شرکت'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contractor',
            name='subtitle',
            field=models.TextField(blank=True, verbose_name='توضیحات برای بنر'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='successful_project',
            field=models.PositiveIntegerField(default=0, verbose_name='پروژه های موفق'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='work_experience',
            field=models.PositiveIntegerField(default=0, help_text='سال', verbose_name='سابقه کار'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('image', models.ImageField(max_length=255, upload_to='projects/gallery/%Y/%m/%d/', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='تگ آلت')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='موضوع')),
                ('subtitle', models.CharField(blank=True, max_length=255, null=True, verbose_name='توضیحات کوتاه')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='contractor.contractor', verbose_name='')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
    ]
