# Generated by Django 4.2.7 on 2026-01-12 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0002_registrationcontractor_alter_contractor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='contractor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='galleries', to='contractor.contractor', verbose_name='سازنده'),
        ),
    ]
