# Generated by Django 4.2.7 on 2026-01-21 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0003_alter_gallery_contractor'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractor',
            name='canonical_link',
            field=models.URLField(blank=True, help_text='تگ کنونیکال به جلوگیری از محتوای تکراری کمک می\u200cکند.', null=True, verbose_name='لینک کنونیکال'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='page_display_status',
            field=models.SmallIntegerField(choices=[(0, 'پیش\u200cنویس'), (1, 'انتشار')], default=0, verbose_name='وضعیت نمایش صفحه'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='search_engine_description',
            field=models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='توضیحات موتور جستجو'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='search_engine_keywords',
            field=models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='کلیدواژه\u200cهای موتور جستجو'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='search_engine_title',
            field=models.CharField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', max_length=255, null=True, verbose_name='عنوان موتور جستجو'),
        ),
        migrations.AddField(
            model_name='contractor',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='temporary-slug', max_length=255, unique=True, verbose_name='اسلاگ'),
            preserve_default=False,
        ),
    ]
