# Generated by Django 4.2.7 on 2025-11-20 08:25

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('page_display_status', models.SmallIntegerField(choices=[(0, 'پیش\u200cنویس'), (1, 'انتشار')], default=0, verbose_name='وضعیت نمایش صفحه')),
                ('search_engine_title', models.CharField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_description', models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_keywords', models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='کلیدواژه\u200cهای موتور جستجو')),
                ('canonical_link', models.URLField(blank=True, help_text='تگ کنونیکال به جلوگیری از محتوای تکراری کمک می\u200cکند.', null=True, verbose_name='لینک کنونیکال')),
                ('title', models.CharField(max_length=225, verbose_name='موضوع')),
                ('image', models.ImageField(blank=True, null=True, upload_to='blog/%y/%m/%d/', verbose_name='تصویر')),
                ('banner_description', models.TextField(verbose_name='توضیحات بنر')),
                ('full_description', ckeditor.fields.RichTextField(verbose_name='محتوا')),
                ('newest_blog', models.ManyToManyField(blank=True, related_name='related_to', to='blog.blog', verbose_name='جدیدترین مطالب')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('-created',),
            },
        ),
    ]
