# Generated by Django 4.2.7 on 2025-11-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blogcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='تگ آلت'),
        ),
    ]
