# Generated by Django 4.2.7 on 2025-12-18 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteglobalsetting',
            name='fee_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد کارمزد'),
        ),
        migrations.AddField(
            model_name='siteglobalsetting',
            name='investment_pending_expire_minutes',
            field=models.PositiveIntegerField(default=15, help_text='مدت زمانی که کاربر برای پرداخت سرمایه\u200cگذاری فرصت دارد', verbose_name='مدت زمان اعتبار پرداخت (دقیقه)'),
        ),
        migrations.AddField(
            model_name='siteglobalsetting',
            name='tax_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='درصد مالیات'),
        ),
    ]
