# Generated by Django 4.2.7 on 2025-11-29 05:35

import ckeditor.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import project.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('areas', '0001_initial'),
        ('contractor', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('page_display_status', models.SmallIntegerField(choices=[(0, 'پیش\u200cنویس'), (1, 'انتشار')], default=0, verbose_name='وضعیت نمایش صفحه')),
                ('search_engine_title', models.CharField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_description', models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_keywords', models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='کلیدواژه\u200cهای موتور جستجو')),
                ('canonical_link', models.URLField(blank=True, help_text='تگ کنونیکال به جلوگیری از محتوای تکراری کمک می\u200cکند.', null=True, verbose_name='لینک کنونیکال')),
                ('title', models.CharField(max_length=255, verbose_name='نام پروژه')),
                ('usage_type', models.CharField(choices=[('residential', 'مسکونی'), ('commercial', 'تجاری'), ('office', 'اداری'), ('mixed', 'ترکیبی')], max_length=50, verbose_name='نوع کاربری')),
                ('profit_to_date', models.PositiveIntegerField(verbose_name='سود محقق شده')),
                ('invest_start_from', models.PositiveIntegerField(verbose_name='مبلغ شروع سرمایه گذاری')),
                ('floor_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد طبقه')),
                ('unit_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد واحد')),
                ('usable_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ مفید')),
                ('estimated_completion_date', models.DateField(verbose_name='تاریخ پیش بینی شده')),
                ('start_date', models.DateField(verbose_name='تاریخ شروع')),
                ('project_details', ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='اطلاعات پروژه')),
                ('address', models.TextField(verbose_name='آدرس')),
                ('map', models.TextField(blank=True, help_text='کد embed گوگل مپ', null=True, verbose_name='نقشه')),
                ('price_per_meter', models.PositiveIntegerField(verbose_name='قیمت هر متر')),
                ('total_area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='متراژ کل')),
                ('complete_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='متراژ تکمیل شده')),
                ('bedroom_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد خواب')),
                ('parking_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد پارکینگ')),
                ('warehouse_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='تعداد انباری')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.city', verbose_name='شهر')),
                ('contractor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to='contractor.contractor', verbose_name='سازندگان')),
                ('province', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='areas.province', verbose_name='استان')),
            ],
            options={
                'verbose_name': 'پروژه',
                'verbose_name_plural': 'پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='ProjectStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='وضعیت پروژه')),
            ],
            options={
                'verbose_name': 'وضعیت پروژه',
                'verbose_name_plural': 'وضعیت پروژه ها',
            },
        ),
        migrations.CreateModel(
            name='ProjectProgressReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('pdf', models.FileField(upload_to='projects/docs/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf']), project.models.ProjectProgressReport.validate_file_size], verbose_name='گزارش پیشرفت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_reports', to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'گزارش پیشرفت',
                'verbose_name_plural': 'گزارش پیشرفت',
            },
        ),
        migrations.CreateModel(
            name='ProjectDocuments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('pdf', models.FileField(upload_to='projects/documents/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf']), project.models.ProjectDocuments.validate_file_size], verbose_name='اسناد پروژه')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='project.project', verbose_name='پروژه')),
            ],
            options={
                'verbose_name': 'سند پروژه',
                'verbose_name_plural': 'اسناد پروژه',
            },
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='project.projectstatus', verbose_name='وضعیت پروژه'),
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('image', models.ImageField(max_length=255, upload_to='projects/gallery/%y/%m/%d/', verbose_name='تصویر')),
                ('alt', models.CharField(blank=True, max_length=255, null=True, verbose_name='تگ آلت')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='project.project', verbose_name='')),
            ],
            options={
                'verbose_name': 'گالری',
                'verbose_name_plural': 'گالری ها',
            },
        ),
    ]
