# Generated by Django 4.2.7 on 2025-12-03 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contractor', '0001_initial'),
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='contractor',
        ),
        migrations.AddField(
            model_name='project',
            name='contractors',
            field=models.ManyToManyField(related_name='projects', to='contractor.contractor', verbose_name='سازنده'),
        ),
        migrations.AddField(
            model_name='project',
            name='is_featured',
            field=models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی؟'),
        ),
        migrations.AlterField(
            model_name='project',
            name='invest_start_from',
            field=models.PositiveIntegerField(help_text='تومان', verbose_name='مبلغ شروع سرمایه گذاری'),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_per_meter',
            field=models.PositiveIntegerField(help_text='تومان', verbose_name='قیمت هر متر'),
        ),
        migrations.AlterField(
            model_name='project',
            name='profit_to_date',
            field=models.CharField(max_length=50, verbose_name='سود محقق شده'),
        ),
    ]
