# Generated by Django 4.2.7 on 2025-12-04 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_remove_project_contractor_project_contractors_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(max_length=255, upload_to='projects/gallery/%Y/%m/%d/', verbose_name='تصویر'),
        ),
    ]
