# Generated by Django 4.2.7 on 2025-12-04 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_alter_gallery_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='current_funding',
            field=models.PositiveIntegerField(default=0, help_text='مقدار سرمایه\u200cای که تاکنون جمع شده', verbose_name='سرمایه فعلی جمع\u200cآوری شده'),
        ),
        migrations.AddField(
            model_name='project',
            name='total_budget',
            field=models.PositiveIntegerField(default=0, help_text='حداکثر سرمایه مورد نیاز برای پروژه (تومان)', verbose_name='بودجه کل پروژه'),
            preserve_default=False,
        ),
    ]
