# Generated by Django 4.2.7 on 2025-12-18 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_project_current_funding_project_total_budget'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='multiplier',
            field=models.PositiveIntegerField(default=0, verbose_name='ماکزیمم قیمت فروش'),
        ),
    ]
