# Generated by Django 4.2.7 on 2025-12-20 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_project_multiplier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='multiplier',
        ),
        migrations.AddField(
            model_name='project',
            name='investable_area',
            field=models.DecimalField(decimal_places=6, default=0, max_digits=14, verbose_name='متراژ قابل سرمایه\u200cگذاری'),
            preserve_default=False,
        ),
    ]
