# Generated by Django 4.2.7 on 2025-11-19 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('slug', models.SlugField(allow_unicode=True, max_length=255, unique=True, verbose_name='اسلاگ')),
                ('page_display_status', models.SmallIntegerField(choices=[(0, 'پیش\u200cنویس'), (1, 'انتشار')], default=0, verbose_name='وضعیت نمایش صفحه')),
                ('search_engine_title', models.CharField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', max_length=255, null=True, verbose_name='عنوان موتور جستجو')),
                ('search_engine_description', models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='توضیحات موتور جستجو')),
                ('search_engine_keywords', models.TextField(blank=True, help_text='اگر خالی باشد، پیش\u200cنمایش آنچه به\u200cصورت خودکار تولید می\u200cشود نمایش داده می\u200cشود.', null=True, verbose_name='کلیدواژه\u200cهای موتور جستجو')),
                ('canonical_link', models.URLField(blank=True, help_text='تگ کنونیکال به جلوگیری از محتوای تکراری کمک می\u200cکند.', null=True, verbose_name='لینک کنونیکال')),
                ('name', models.CharField(max_length=225, unique=True, verbose_name='نام دسته\u200cبندی')),
            ],
            options={
                'verbose_name': 'دسته\u200cبندی',
                'verbose_name_plural': 'دسته\u200cبندی\u200cها',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('question', models.CharField(max_length=255, verbose_name='صورت سؤال')),
                ('answer', models.TextField(verbose_name='پاسخ')),
                ('is_featured', models.BooleanField(default=False, verbose_name='نمایش در صفحه اصلی؟')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faqs', to='faqs.category', verbose_name='دسته\u200cبندی موضوع')),
            ],
            options={
                'verbose_name': 'سؤال متداول',
                'verbose_name_plural': 'سؤالات متداول',
                'ordering': ['-created'],
            },
        ),
    ]
