# Generated by Django 4.2.7 on 2025-11-01 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rules',
            options={'verbose_name': ('قوانین و مقررات',), 'verbose_name_plural': 'قوانین و مقررات'},
        ),
        migrations.AlterField(
            model_name='rules',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان '),
        ),
    ]
