# Generated by Django 4.2.7 on 2026-01-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rules',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان'),
        ),
    ]
