# Generated by Django 4.2.7 on 2026-01-25 09:50

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rules_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rules',
            name='canonical_link',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='page_display_status',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='search_engine_description',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='search_engine_keywords',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='search_engine_title',
        ),
        migrations.RemoveField(
            model_name='rules',
            name='slug',
        ),
        migrations.AddField(
            model_name='rules',
            name='description',
            field=ckeditor.fields.RichTextField(default='No description', verbose_name='محتوا'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RuleItem',
        ),
    ]
