# Generated by Django 4.2.7 on 2025-11-09 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rules', '0002_alter_rules_options_alter_rules_title'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ruleitem',
            options={'ordering': ['order'], 'verbose_name': 'آیتم قانون', 'verbose_name_plural': 'آیتم های قانون'},
        ),
    ]
