# Generated by Django 4.2.7 on 2025-11-08 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteGlobalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('address', models.TextField(blank=True, null=True, verbose_name='آدرس')),
                ('map', models.TextField(blank=True, help_text='کد embed گوگل مپ', null=True, verbose_name='نقشه')),
            ],
            options={
                'verbose_name': 'پیکربندی سایت',
                'verbose_name_plural': 'پیکربندی سایت',
            },
        ),
    ]
