# Generated by Django 4.2.7 on 2025-11-12 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialMediaSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='ایجاد شده')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='آپدیت شده')),
                ('name', models.CharField(max_length=100, verbose_name='نام')),
                ('username_or_id', models.CharField(help_text='مثال: firefly@', max_length=100, verbose_name='نام کاربری یا آیدی')),
                ('icon', models.CharField(blank=True, help_text='به صورت پیشفرض از fontawesome پشتیبانی می شود، فقط کافیست نام آیکون را وارد کنید. برای مثال: facebook', max_length=100, null=True, verbose_name='آیکون')),
                ('link', models.URLField(verbose_name='لینک')),
            ],
            options={
                'verbose_name': 'شبکه اجتماعی',
                'verbose_name_plural': 'شبکه های اجتماعی',
            },
        ),
    ]
