# Generated by Django 4.2.7 on 2025-11-12 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteinfo', '0002_socialmediasetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='siteglobalsetting',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='ایمیل'),
        ),
        migrations.AddField(
            model_name='siteglobalsetting',
            name='phone',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='شماره تلفن'),
        ),
    ]
